apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpl-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fpl-frontend
  template:
    metadata:
      labels:
        app: fpl-frontend
    spec:
      containers:
        - name: fpl-frontend
          image: bimalpaudel/fpl-frontend:v0.3
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://192.168.2.73:30001"
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
