apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: fpl-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30002
  type: NodePort
